/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import Navbar from "../Navbar";
import { api } from "../../lib/api";
import { useAuth } from "../../authContext";

const RepoCard = ({ repo, mine, onDelete, onToggle }) => <article className="repo-card"><div className="repo-card-top"><span className="repo-icon">⌘</span><span className={`badge ${repo.visibility ? "private" : "public"}`}>{repo.visibility ? "Private" : "Public"}</span></div><Link to={`/repository/${repo._id}`}><h3>{repo.name}</h3></Link><p>{repo.description || "No description yet — add some context for your team."}</p><footer><span>{repo.issues?.length || 0} issues</span>{mine && <span className="actions"><button onClick={() => onToggle(repo._id)}>{repo.visibility ? "Make public" : "Make private"}</button><button className="danger" onClick={() => onDelete(repo._id)}>Delete</button></span>}</footer></article>;

export default function Dashboard() {
  const { currentUser } = useAuth(); const [myRepos, setMyRepos] = useState([]); const [allRepos, setAllRepos] = useState([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const [mine, all] = await Promise.all([api.myRepos(currentUser).catch(() => []), api.repos()]); setMyRepos(Array.isArray(mine) ? mine : []); setAllRepos(Array.isArray(all) ? all : []); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { if (currentUser) load(); }, [currentUser]);
  const visible = useMemo(() => myRepos.filter(repo => repo.name.toLowerCase().includes(query.toLowerCase())), [myRepos, query]);
  const remove = async id => { if (!window.confirm("Delete this repository? This cannot be undone.")) return; try { await api.deleteRepo(id); load(); } catch (e) { setError(e.message); } };
  const toggle = async id => { try { await api.toggleRepo(id); load(); } catch (e) { setError(e.message); } };
  const explore = allRepos.filter(repo => String(repo.owner?._id || repo.owner) !== String(currentUser)).slice(0, 3);
  return <><Navbar /><main className="shell"><section className="page-intro"><div><p className="eyebrow">YOUR WORKSPACE</p><h1>Good to see you.</h1><p className="muted">Everything you’re building, in one focused place.</p></div><Link className="button" to="/create">+ Create repository</Link></section><section className="metrics"><div><span>Repositories</span><strong>{myRepos.length}</strong></div><div><span>Open issues</span><strong>{myRepos.reduce((total, repo) => total + (repo.issues?.filter(issue => issue.status !== "CLOSE").length || 0), 0)}</strong></div><div><span>Visibility</span><strong>{myRepos.filter(repo => !repo.visibility).length} public</strong></div></section>{error && <p className="form-error page-error">{error}</p>}<section className="workspace-grid"><div className="main-column"><div className="section-heading"><div><h2>Your repositories</h2><p>Pick up where you left off.</p></div><label className="search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search repositories" /></label></div>{loading ? <div className="empty-state">Loading your workspace…</div> : visible.length ? <div className="repo-grid">{visible.map(repo => <RepoCard key={repo._id} repo={repo} mine onDelete={remove} onToggle={toggle} />)}</div> : <div className="empty-state"><h3>{query ? "No matches found" : "Start your first repository"}</h3><p>{query ? "Try a different search." : "Create a repository to organize code and issues."}</p>{!query && <Link className="button" to="/create">Create repository</Link>}</div>}</div><aside className="side-column"><div className="side-heading"><h2>Explore</h2></div>{explore.length ? explore.map(repo => <Link className="explore-row" key={repo._id} to={`/repository/${repo._id}`}><span className="repo-icon">⌘</span><span><strong>{repo.name}</strong><small>{repo.owner?.username || "HubForge member"}</small></span></Link>) : <p className="muted small">New team repositories will appear here.</p>}<div className="tip-card"><span>✦</span><h3>Keep momentum</h3><p>Turn important work into issues and close the loop as you ship.</p></div></aside></section></main></>;
}
