/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import Navbar from "../Navbar";
import { api } from "../../lib/api";

export default function Repository() {
  const { id } = useParams();
  const [repo, setRepo] = useState(null), [issues, setIssues] = useState([]), [files, setFiles] = useState([]);
  const [form, setForm] = useState({ title: "", description: "" }), [error, setError] = useState(""), [storageError, setStorageError] = useState("");
  const load = async () => { try { const [repository, issueData] = await Promise.all([api.repo(id), api.issues(id).catch(() => [])]); setRepo(repository); setIssues(issueData); try { setFiles(await api.repoFiles(id)); setStorageError(""); } catch (failure) { setFiles([]); setStorageError(failure.message); } } catch (e) { setError(e.message); } };
  useEffect(() => { load(); }, [id]);
  const add = async (event) => { event.preventDefault(); try { await api.createIssue({ ...form, repositoryId: id }); setForm({ title: "", description: "" }); load(); } catch (err) { setError(err.message); } };
  const toggle = async (issue) => { try { await api.updateIssue(issue._id, { status: issue.status === "CLOSE" ? "OPEN" : "CLOSE" }); load(); } catch (err) { setError(err.message); } };
  const download = async (file) => { try { const blob = await api.downloadRepoFile(id, file.path, file.commitId); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = file.path.split("/").pop(); anchor.click(); URL.revokeObjectURL(url); } catch (err) { setStorageError(err.message); } };
  if (!repo && !error) return <><Navbar /><main className="shell empty-state">Loading repository...</main></>;
  return <><Navbar /><main className="shell"><Link className="back-link" to="/dashboard">← Workspace</Link>{error && <p className="form-error">{error}</p>}{repo && <><section className="repo-hero"><div><p className="eyebrow">{repo.owner?.username || "PROJECT"} / REPOSITORY</p><h1>{repo.name}</h1><p className="muted">{repo.description || "No description provided."}</p></div><span className={`badge ${repo.visibility ? "private" : "public"}`}>{repo.visibility ? "Private" : "Public"}</span></section><section className="issue-layout"><div><div className="section-heading"><div><h2>Issues</h2><p>{issues.filter((issue) => issue.status !== "CLOSE").length} open · {issues.length} total</p></div></div><div className="issue-list">{issues.length ? issues.map((issue) => <article className="issue" key={issue._id}><span className={issue.status === "CLOSE" ? "issue-status closed" : "issue-status"}>{issue.status === "CLOSE" ? "✓" : "○"}</span><div><h3>{issue.title}</h3><p>{issue.description}</p></div><button className="text-button" onClick={() => toggle(issue)}>{issue.status === "CLOSE" ? "Reopen" : "Close"}</button></article>) : <div className="empty-state">No issues yet. Add the first piece of work below.</div>}</div><section className="synced-files"><h2>Synced files</h2>{storageError ? <p className="form-error">Storage unavailable: {storageError}</p> : files.length ? files.map((file) => <p key={file.path}>⌘ <code>{file.path}</code> <small>{file.size} bytes · {file.versionCount} version{file.versionCount === 1 ? "" : "s"}</small><button className="download-file" onClick={() => download(file)}>Download</button></p>) : <p className="muted">No files pushed yet.</p>}</section></div><aside className="new-issue"><h2>New issue</h2><p>Capture work while it’s fresh.</p><form onSubmit={add}><label>Title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="What needs attention?" /></label><label>Description<textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Give your team some context" /></label><button className="button full">Create issue</button></form></aside></section></>}</main></>;
}
