import { Link } from "react-router-dom";

const features = [
  ["⌘", "Projects that stay clear", "Give every repository a focused home, with the context your team needs."],
  ["◎", "Issues with momentum", "Capture the work that matters and move it from open to shipped."],
  ["↗", "Built for forward motion", "A calmer workspace that makes the next right step obvious."],
];

export default function Landing() {
  return <main className="landing"><header className="landing-nav"><Link className="brand" to="/"><span className="brand-mark">H</span>HubForge</Link><nav><a href="#features">Why HubForge</a><Link to="/auth">Sign in</Link><Link className="button button-small" to="/signup">Start for free</Link></nav></header><section className="landing-hero"><p className="eyebrow">THE DEVELOPER WORKSPACE, REFINED</p><h1>Make space for<br /><em>better building.</em></h1><p className="hero-copy">HubForge gives your projects, repositories, and issues one thoughtful place to move from idea to shipped.</p><div className="hero-actions"><Link className="button" to="/signup">Create your workspace <span>→</span></Link><Link className="play-link" to="/auth"><span>▶</span> See your workspace</Link></div><div className="hero-orbit"><div className="orbit-card orbit-repo"><span className="repo-icon">⌘</span><div><strong>atlas-api</strong><small>Repository · Active</small></div><i>•••</i></div><div className="orbit-card orbit-issue"><span className="issue-dot">○</span><div><strong>Refine onboarding</strong><small>Issue · In progress</small></div></div><div className="orbit-center"><span>H</span><b>Your best work<br />starts here.</b></div><span className="star star-a">✦</span><span className="star star-b">✦</span><span className="star star-c">✦</span></div></section><section id="features" className="feature-section"><p className="eyebrow">DESIGNED FOR THE WAY YOU WORK</p><h2>Everything you need.<br />Nothing pulling you away.</h2><div className="feature-grid">{features.map(([icon, title, copy]) => <article key={title}><span>{icon}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="landing-cta"><p className="eyebrow">YOUR NEXT PROJECT IS WAITING</p><h2>Begin with a little more clarity.</h2><Link className="button" to="/signup">Start building free <span>→</span></Link></section><footer className="landing-footer"><span className="brand"><span className="brand-mark">H</span>HubForge</span><span>© 2026 HubForge. Made for makers.</span><Link to="/auth">Sign in</Link></footer></main>;
}
